version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  azure-aks: circleci/azure-aks@0.3.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  docker-config:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Grade build
          command: ./gradlew clean build
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_LOGIN/$APP_NAME:latest .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$APP_NAME:latest
  aks-deploy:
    docker:
      - image: cimg/base:current
    parameters:
      cluster-name:
        description: |
          Name of the AKS cluster.
        type: string
      resource-group:
        description: |
          Resource group that the cluster is in
        type: string
    steps:
      - checkout
      - run:
          name: Pull Updated code from repo
          command: git pull origin $CIRCLE_BRANCH
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          perform-login: true
          resource-group: << parameters.resource-group >>
      - kubernetes/create-or-update-resource:
          resource-file-path: manifests/$APP_NAME.yaml
          resource-name: kustomization/$APP_NAME

  bump-docker-tag-kustomize:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Install kustomize
          command: |
            URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.2/kustomize_v4.5.2_linux_amd64.tar.gz
            curl -L $URL | tar zx
            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO chmod +x ./kustomize
            $SUDO mv ./kustomize /usr/local/bin
      - checkout
      - run:
          name: Bump Docker Tags
          command: |
            cd manifests
            kustomize edit set image $APP_NAME=$DOCKER_LOGIN/$APP_NAME:$CIRCLE_SHA1
            kustomize build . > $APP_NAME.yaml
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: Commit & Push to GitHub
          command: |
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI User"
            git checkout $CIRCLE_BRANCH           
            git add manifests/$APP_NAME.yaml
            git add manifests/kustomization.yaml
            git commit -am "Bumps docker tag [skip ci]"
            git push origin $CIRCLE_BRANCH

  apply-autoscaler:
    docker:
      - image: alpine:latest
          # Install kubectl (if using this approach)
          - apk add --no-cache kubectl

    steps: # Make sure the steps section is indented under the job definition
      - checkout
      - run:
          name: Apply HorizontalPodAutoscaler
          command: kubectl apply -f manifests/hpa-mongodb.yaml



workflows:
  Deploy-App-on-AKS:
    jobs:
      - docker-config
      - bump-docker-tag-kustomize:
          requires:
            - docker-config
      - aks-deploy:
          cluster-name: $CLUSTER_NAME
          resource-group: $RESOURCE_GROUP
          requires:
            - bump-docker-tag-kustomize
          context:
            - wanderquest
      - apply-autoscaler:
          requires:
            - aks-deploy
