apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderquest-backend
  namespace: wanderquest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanderquest-backend
  template:
    metadata:
      labels:
        app: wanderquest-backend
    spec:
      containers:
        - name: test
          image: sandervandeurzen/wanderquestbackendtovm:latest
          ports:
            - containerPort: 8080
