apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- autoscaling.yaml
namespace: wanderquest-backend
images:
- name: wanderquest-backend-aks-app
  newName: sandervandeurzen/wanderquest-backend-aks-app
  newTag: 58d9d4a252d31ae3f4fe89c7f0ecee9806691afb
