apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: wanderquest-backend
images:
- name: wanderquest-backend-aks-app
  newName: sandervandeurzen/wanderquest-backend-aks-app
  newTag: 4b7de91baa14e9072c9feb3d0aa5c6fc1400eefb
