apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- hpa-mongodb.yaml
namespace: wanderquest-backend
images:
- name: wanderquest-backend-aks-app
  newName: sandervandeurzen/wanderquest-backend-aks-app
  newTag: 72cd0162890aee0be469c6fa94a90707d3bed996
