apiVersion: v1
kind: Service
metadata:
  name: wanderquest-backend
  namespace: wanderquest-backend
spec:
  selector:
    app: wanderquest-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # Change to LoadBalancer

  