apiVersion: v1
kind: Service
metadata:
  name: wanderquest-backend
spec:
  selector:
    app: wanderquest-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: LoadBalancer
  