apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: wanderquest-backend
  name: wanderquest-backend
---
apiVersion: v1
kind: Service
metadata:
  name: wanderquest-backend
  namespace: wanderquest-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wanderquest-backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderquest-backend
  namespace: wanderquest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanderquest-backend
  template:
    metadata:
      labels:
        app: wanderquest-backend
    spec:
      containers:
      - image: sandervandeurzen/wanderquest-backend:latest
        name: test
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb-hpa
  namespace: wanderquest-backend
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongodb
