name: Run JMeter Tests

on:
  push:
    branches:
      - main  # Voer de workflow uit bij elke push naar de main branch

jobs:
  run_jmeter_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Haal de repository op om toegang te krijgen tot de bestanden

      - name: Download and extract Apache JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xf apache-jmeter-5.6.3.tgz
        working-directory: ${{ github.workspace }}  # Werk vanuit de hoofdmap van de repository

      - name: Run JMeter tests
        run: |
          cd apache-jmeter-5.6.3/bin
          ./jmeter -n -t ../../jmeter/test-plan.jmx -l results.jtl
          cat results.jtl | grep false && exit 1  # Laat de workflow mislukken als er 'false' (mislukkingen) worden gedetecteerd in de resultaten
        working-directory: ${{ github.workspace }}  # Werk vanuit de hoofdmap van de repository

      - name: Upload test results
        if: success()  # Upload de testresultaten alleen als de JMeter-tests succesvol waren
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: apache-jmeter-5.6.3/bin/results.jtl
